Eric906/localserver shapefile sample
Esri/arcgis-maps-sdk-java-samples pull request #144
Opened 2017-05-23 06:41 UTC by john0005

@eric906 Re-created your PR to dev branch.

Initial creation of sample code, PNG and README for LocalServerDynamicWorkspaceRaster.
Note: We also need to add "shapefiles" folder to the master samples-data zip. I can do that.

2017-05-23 14:00 UTC, john0005 commented
@eric906 Do you have the location of the shape file you used in this sample?

2017-05-23 16:14 UTC, tyle8552 commented
@john0005 I'm updating the samples data with the shapefiles right now.

2017-05-23 16:22 UTC, tyle8552 commented
Hmm, for some reason I'm not able to update the samples data. It just uploads forever. I'll slack you the shapefile location so you can give it a try.

2017-05-24 11:51 UTC, john0005 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/LocalServerDynamicWorkspaceShapefileSample.java
> +            imageLayer.getSublayers().add(shapefileSublayer);
Would add code below to zoom to shapefile location.
```java
shapefileSublayer.addDoneLoadingListener(() -> {
  mapView.setViewpoint(new Viewpoint(shapefileSublayer.getMapServiceSublayerInfo().getExtent()));
});
shapefileSublayer.loadAsync();
```

2017-05-24 11:51 UTC, john0005 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/README.md
> +<p>A Local Server and Local Map Service will automatically be started and once running a Feature Layer will be created and added to the map. </p>
Would change this to read like below,
A Local Server will automatically start once application is running. Select a shapefile using the `Choose Shapefile` button which will automatically start a Local Map Service where a Dynamic Shapefile Workspace will be set and displayed to the Map View.

2017-05-24 11:51 UTC, john0005 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/README.md
> +<li><code>Server.startAsync()</code> starts the server asynchronously</li></ul>
I would fit this in under `1` as another bullet.

2017-05-24 11:51 UTC, john0005 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/README.md
> +<li>Create the <code>ShapefileWorkspace</code> and <code>TableSublayerSource</code> instances.</li>
Would split these two up and have it something like,
```
Create a <code>ShapefileWorkspace</code>  with id 'shp_wkspc' and absolute path to location of were shapefile is being stored.
Create a <code>TableSublayerSource</code>  using  <code>shapefileWorkspace.getId()</code> and name of  shapefile with extension, example `mjrroads.shp`.
```

2017-05-24 11:51 UTC, john0005 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/README.md
> +<li>Add the <code>ShapefileWorkspace</code> the list of dynamic workspaces of the <code>LocalMapService</code>.</li>
<li>Add <code>ShapefileWorkspace</code> to  <code>LocalMapService.setDynamicWorkspaces()</code>.</li>

2017-05-24 11:51 UTC, john0005 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/README.md
> +<ul><li><code>localMapService.addStatusChangedListener()</code> fires whenever the status of the local server has changed.</li></ul></li>
would probably switch the order of line 26 and 27.

2017-05-24 11:51 UTC, john0005 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/README.md
> +<li>Create a <code>ArcGISMapImageLayer</code> using the url from the <code>localMapService</code></li>
<li>Create a <code>ArcGISMapImageLayer</code> using <code>localMapService.getUrl()</code></li>

2017-05-24 11:51 UTC, john0005 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/README.md
> +<li>Add the ArcGISMapImageSublayer to it's list of sublayers. The ArcGISMapImageSublayer points to the shapefile file on disk.
Would say something like,
```
Once <code>ArcGISMapImageLayer</code> is done loading,  set <code>ArcGISMapImageSublayer </code> to <code>ArcGISMapImageLayer.getSublayers()</code>. The ArcGISMapImageSublayer points to the shapefile file on disk.
```

2017-05-24 11:52 UTC, john0005 commented
@eric906 Some changes, still have to get files onto AGOL.

2017-05-24 15:46 UTC, tyle8552 commented
@eric906 @john0005 The samples data should be updated to include the shapefiles now

2017-05-24 17:19 UTC, eric906 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/LocalServerDynamicWorkspaceShapefileSample.java
> +            imageLayer.getSublayers().add(shapefileSublayer);
Cool. I had that in, then removed it. Doh. I'll add it back in.

2017-05-24 19:00 UTC, ghost requested changes
Looks good. A few minor changes.

2017-05-24 19:00 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/LocalServerDynamicWorkspaceShapefileSample.java
> +package com.esri.samples.localserver.local_server_dynamic_workspace_shp;
package name has to be the same as the sample: `local_server_dynamic_workspace_shapefile`.

2017-05-24 19:00 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/LocalServerDynamicWorkspaceShapefileSample.java
> +      stage.setTitle("Dynamic workspaces: shapefile");
Should be the full name: `Local Server Dynamic Workspace Shapefile Sample`.

2017-05-24 19:00 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/LocalServerDynamicWorkspaceShapefileSample.java
> +        FileChooser fileChooser = new FileChooser();
The file chooser can be created outside of this event listener and reused.

2017-05-24 19:00 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/LocalServerDynamicWorkspaceShapefileSample.java
> +    // Can't add a dynamic workspace to a running service, so do that first
less colloquial language. should be more direct to follow the pattern set in other samples. Just `//create a shapefile workspace`.

2017-05-24 19:00 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/LocalServerDynamicWorkspaceShapefileSample.java
> +    TableSublayerSource source = new TableSublayerSource(shapefileWorkspace.getId(), fileName);
Some more comments in here would help explain what's going on.

2017-05-24 19:00 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/LocalServerDynamicWorkspaceShapefileSample.java
> +      // start local server if found
`// check local server is installed`

2017-05-24 19:00 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shp/LocalServerDynamicWorkspaceShapefileSample.java
> +        // Browse to the shapefile file
Keep capitals consistent. We usually start comments (not javadoc) with lowercase.

2017-05-24 19:25 UTC, eric906 commented
@john0005 @tyle8552 Thank you for the edits. I think I've applied them all.

2017-05-24 22:13 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shapefile/README.md
> +<li>StatusChangedEvent</li>
This can be removed. It's not a feature

2017-05-24 22:13 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shapefile/LocalServerDynamicWorkspaceShapefileSample.java
> +package com.esri.samples.localserver.local_server_dynamic_workspace_shapefile;
Need to add copyright text. Just copy from another sample

2017-05-24 22:14 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_dynamic_workspace_shapefile/LocalServerDynamicWorkspaceShapefileSample.java
> +        fileChooser.setTitle("Open Resource File");
I should have been more explicit, sorry. These three lines that setup the file chooser can also go outside of the listener. Basically anything that doesn't need to change every time the button is clicked should be done outside of it.

2017-05-24 22:15 UTC, tyle8552 commented
@eric906 Almost there. After those I'll approve. Thanks

2017-05-24 22:22 UTC, eric906 commented
@tyle8552 Ok, thanks for the work on this. And thanks for being patient. :-)

2017-05-24 23:55 UTC, ghost approved these changes

2017-05-25 15:55 UTC, merged