Updating Samples
Esri/arcgis-maps-sdk-java-samples pull request #172
Opened 2017-07-13 16:05 UTC by john0005

issues: 
  - https://devtopia.esri.com/runtime/java-se-sdk/issues/1055 or https://github.com/Esri/arcgis-runtime-samples-java/issues/113

2017-07-25 18:42 UTC, tschie commented on src/main/java/com/esri/samples/editing/update_geometries/UpdateGeometriesSample.java
> +                FeatureQueryResult result = featureLayer.getSelectedFeaturesAsync().get();
I don't think we should use a blocking `get` here. Also, we shouldn't keep track of a `selected` feature if we're just going to check for it every time.

2017-07-25 18:45 UTC, tschie commented on src/main/java/com/esri/samples/symbology/symbol_dictionary/SymbolDictionaryController.java
> +            symbolResults.subList(0, Math.min(results, RESULT_SIZE)).stream().map(SymbolView::new).collect(Collectors.toCollection(() -> resultList.getItems()));
There's an official `Pagination` control for this that you should use: http://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Pagination.html.

2017-07-25 18:46 UTC, tschie requested changes
Added some suggestions.

2017-07-27 23:51 UTC, tschie commented on src/main/java/com/esri/samples/editing/update_geometries/UpdateGeometriesSample.java
> +                FeatureQueryResult result = featureLayer.getSelectedFeaturesAsync().get();
Can you remove changes for this sample. I have a fix that handles a couple other things as well in another PR: https://github.com/Esri/arcgis-runtime-samples-java/pull/176.

2017-08-01 15:13 UTC, john0005 commented
@tschie Can you look this over again added the Pagination Class.

2017-08-01 22:40 UTC, tschie approved these changes

2017-08-01 22:40 UTC, merged