Tschie/raster function sample
Esri/arcgis-maps-sdk-java-samples pull request #180
Opened 2017-08-28 19:11 UTC by tschie

Added raster function sample. Demonstrates applying a raster function to an image service raster.

Also made two small fixes to RasterLayerURLSample.

2017-08-28 19:12 UTC, tschie commented
@john0005 Can you please review.

2017-08-30 15:26 UTC, john0005 requested changes

2017-08-30 15:26 UTC, john0005 commented on src/main/java/com/esri/samples/raster/raster_function/RasterFunctionSample.java
> +        if (imageServiceRaster.getLoadStatus() == LoadStatus.LOADED) {
Need to be delete it's on the next line as well.

2017-08-30 15:26 UTC, john0005 commented on src/main/java/com/esri/samples/raster/raster_function/RasterFunctionSample.java
> +                rasterFunction.getArguments().setRaster(arguments.getRasterNames().get(0), imageServiceRaster);
`arguments.setRaster(arguments.getRasterNames().get(0), imageServiceRaster);`
Since and `arguments` and `rasterFunction.getArguments()` is the same thing.

2017-08-30 15:26 UTC, john0005 commented on src/main/java/com/esri/samples/raster/raster_function/RasterFunctionSample.java
> +                String json = scanner.useDelimiter("\\A").next();
Would place a comment in here stating that this gets the complete JSON string from the beginning.

2017-08-30 15:26 UTC, john0005 commented on src/main/java/com/esri/samples/raster/raster_function/RasterFunctionSample.java
> +                hillshadeLayer.loadAsync();
Not needed.

2017-08-30 15:28 UTC, john0005 commented
Once merge I will need to retest again. May need to make issues for Mac because the Vector basemap doesn't load the same and every now and then the Image Service Raster doesn't start to load. 

Works fine on windows.

2017-08-30 16:42 UTC, tschie commented
@john0005 Thanks for the review. I've made the changes. I will merge. Let me know if any issues on mac require changes to the sample.

2017-08-30 16:42 UTC, merged

2017-08-31 12:58 UTC, john0005 commented
Vector basemap is working fine now. Image raster only Loads every other time. Weird thing is if you add a Button to the view then the Image raster loads every time. I put it on there to tell me the load status of the Image raster. Once I take it off the image raster only loads every other time again.