Tschie/viewshed samples
Esri/arcgis-maps-sdk-java-samples pull request #191
Opened 2017-11-07 00:54 UTC by tschie

3 samples demonstrating viewshed. Only thing missing is frustum options in ViewshedLocationSample. Will add those later.

2017-11-07 00:54 UTC, tschie commented
@john0005 Can you please review?

2017-11-07 14:15 UTC, john0005 requested changes

2017-11-07 14:15 UTC, john0005 commented on src/main/java/com/esri/samples/analysis/viewshed_camera/README.md
> +<p>Demonstrates how to create and update a viewshed from a camera.</p>
Would add another sentence about what viewshed is. So that way they would understand that green is the area you can see and red is the area you can't.

2017-11-07 14:15 UTC, john0005 commented on src/main/java/com/esri/samples/analysis/viewshed_geoelement/README.md
> +<p><img src="ViewshedCamera.gif"/></p>
Picture is not showing.

2017-11-07 14:15 UTC, john0005 commented on src/main/java/com/esri/samples/analysis/viewshed_geoelement/README.md
> +<p>Demonstrates how to attach a viewshed to a moving GeoElement.</p>
Would add explanation of what viewshed is.

2017-11-07 14:15 UTC, john0005 commented on src/main/java/com/esri/samples/analysis/viewshed_geoelement/ViewshedGeoElementSample.java
> +      String modelURI = new File("./samples-data/bradley_low_3ds/bradle.3ds").getAbsolutePath();
I refreshed the sample data and didn't see this file.

2017-11-07 14:15 UTC, john0005 commented on src/main/java/com/esri/samples/analysis/viewshed_location/README.md
> +<p>Demonstrates how to change the properties of a viewshed.</p>
Explain what a viewshed is.

2017-11-07 14:15 UTC, john0005 commented on src/main/java/com/esri/samples/analysis/viewshed_location/ViewshedLocationController.java
> +    LocationViewshed viewshed = new LocationViewshed(location, headingSlider.getValue(), pitchSlider.getValue(),
Saying Surplacement is not a parameter.

2017-11-07 14:15 UTC, john0005 commented on src/main/java/com/esri/samples/analysis/viewshed_location/ViewshedLocationController.java
> +    sceneView.setOnMouseClicked(event -> {
The first time you do this you have to click twice to move the point.

2017-11-07 14:15 UTC, john0005 commented on src/main/java/com/esri/samples/analysis/viewshed_geoelement/ViewshedGeoElementSample.java
> +  private void animate() {
A brief comment about what it does.

2017-11-07 20:20 UTC, tschie commented on src/main/java/com/esri/samples/analysis/viewshed_geoelement/ViewshedGeoElementSample.java
> +      String modelURI = new File("./samples-data/bradley_low_3ds/bradle.3ds").getAbsolutePath();
I always forget that. Should work now.

2017-11-07 20:20 UTC, tschie commented on src/main/java/com/esri/samples/analysis/viewshed_location/ViewshedLocationController.java
> +    LocationViewshed viewshed = new LocationViewshed(location, headingSlider.getValue(), pitchSlider.getValue(),
There was an API change that removed it. I've updated the api dependency version.

2017-11-07 20:20 UTC, tschie commented
@john0005 Ready for a second review.

2017-11-08 11:26 UTC, john0005 approved these changes

2017-11-08 11:27 UTC, john0005 commented
Everything looks good.

2017-11-08 15:35 UTC, merged