Initial implementation of feature layer geopackage sample
Esri/arcgis-maps-sdk-java-samples pull request #192
Opened 2017-11-08 18:45 UTC by tschie

feature layer geopackage sample

2017-11-08 18:46 UTC, tschie commented
@john0005 Can you please review?

2017-11-09 14:29 UTC, john0005 requested changes

2017-11-09 14:29 UTC, john0005 commented on src/main/java/com/esri/samples/featurelayers/feature_layer_geopackage/FeatureLayerGeoPackageSample.java
> +      File geoPackageFile = new File("./samples-data/auroraCO/AuroraCO.gpkg");
Didn't show up in samples data.

2017-11-09 14:29 UTC, john0005 commented on src/main/java/com/esri/samples/featurelayers/feature_layer_geopackage/FeatureLayerGeoPackageSample.java
> +        }
Would add alert about geopackage not being found.

2017-11-09 18:10 UTC, tschie commented on src/main/java/com/esri/samples/featurelayers/feature_layer_geopackage/FeatureLayerGeoPackageSample.java
> +      File geoPackageFile = new File("./samples-data/auroraCO/AuroraCO.gpkg");
Added it.

2017-11-09 18:13 UTC, tschie commented
@john0005 I've made the changes. Please review again. Thanks.

2017-11-10 09:07 UTC, john0005 approved these changes

2017-11-10 09:07 UTC, john0005 commented
Looks good.

2017-11-10 09:31 UTC, colinanderson commented on src/main/java/com/esri/samples/featurelayers/feature_layer_geopackage/FeatureLayerGeoPackageSample.java
> +      File geoPackageFile = new File("./samples-data/auroraCO/AuroraCO.gpkg");
A more modern way would be to do something like `Paths.get("./samples-data/auroraCO/AuroraCO.gpkg").toAbsolutePath()`.

2017-11-10 16:58 UTC, merged