open street map layer #129
Esri/arcgis-maps-sdk-java-samples pull request #274
Opened 2018-09-18 23:13 UTC by markjdugger

I created OpenStreetMapLayerSample using Basemap.Type.OPEN_STREET_MAP.
Originally, I compared two different approaches:
1. Create an ArtcGISMap by passing OPEN_STREET_MAP type of Basemap>
     - Rationale explained Lucas Danzinger's 2017-04-21 comment  (in #129 above)

1. Create an OpenStreetMapLayer and then add layer to the map's layer list.
     - Rationale explained by my 2018-09-14 comment (also in #129 above)
Ultimately, I chose Option 1.

2018-09-18 23:14 UTC, markjdugger commented
@tschie Do you accept Lucas Danzinger's design rationale, as explained in his comment of 2017-04-21?

2018-09-18 23:31 UTC, markjdugger commented
I also got thoughtful responses on this issue via Slack thread:
https://esri-runtime.slack.com/archives/C0HPF1Q87/p1537192449000100?thread_ts=1536968748.000100&cid=C0HPF1Q87
Lucas Danzinger's "final" word convinced me:

> I think the most common use case for displaying a OSM Layer is to set the map/scene’s basemap to OSM, so I think it makes more sense to have it be in the basemap and not operational layer list

2018-09-19 06:30 UTC, markjdugger commented
this is test
- [x] design runtime/common-samples#129

2018-09-19 06:33 UTC, markjdugger commented
#129

2018-09-19 06:35 UTC, markjdugger commented
[](url)

2018-09-19 06:39 UTC, markjdugger commented
*https://devtopia.esri.com/runtime/common-samples/issues/129

2018-09-21 23:23 UTC, markjdugger commented
@tschie Do you approve this PR?

2018-09-24 07:27 UTC, tschie requested changes
Great first start! I've suggested a few changes based on the sample implementation guidelines (I sent you a link separately). Please re-request review after you've made the changes.

2018-09-24 07:27 UTC, tschie commented on src/main/java/com/esri/samples/ogc/open_street_map_layer/OpenStreetMapLayerSample.java
> + * Copyright 2017 Esri.
need to change to 2018

2018-09-24 07:27 UTC, tschie commented on src/main/java/com/esri/samples/ogc/open_street_map_layer/OpenStreetMapLayerSample.java
> +
remove new line

2018-09-24 07:27 UTC, tschie commented on src/main/java/com/esri/samples/ogc/open_street_map_layer/OpenStreetMapLayerSample.java
> +      // create an ArcGISMap with an OPEN_STREET_MAP basemap
create ~~an ArcGISMap~~ map with an ~~OPEN_STREET_MAP~~ OpenStreetMap basemap

2018-09-24 07:27 UTC, tschie commented on src/main/java/com/esri/samples/ogc/open_street_map_layer/OpenStreetMapLayerSample.java
> +      // set the map to be displayed in this view
set the map to a map view

2018-09-24 07:27 UTC, tschie commented on src/main/java/com/esri/samples/ogc/open_street_map_layer/OpenStreetMapLayerSample.java
> +      stackPane.getChildren().addAll(mapView);
addAll -> add

2018-09-24 07:27 UTC, tschie commented on src/main/java/com/esri/samples/ogc/open_street_map_layer/README.md
> +
This file needs to be in html while still having the .md extension. The reason is the sample viewer renders these in a webview as html. Look at the raw text of some of the other sample readmes to get an idea of the format.

2018-09-24 07:27 UTC, tschie commented on src/main/java/com/esri/samples/ogc/open_street_map_layer/README.md
> +![OpenStreetMap Layer App](openstreetmap-layer.png)
The image needs to be 800w by 400h.

2018-09-24 07:27 UTC, tschie commented on src/main/java/com/esri/samples/ogc/open_street_map_layer/README.md
> +## How to use the sample
You can just omit this section for basic samples like this one.

2018-09-24 07:27 UTC, tschie commented on src/main/java/com/esri/samples/ogc/open_street_map_layer/README.md
> +Instantiate an `ArcGISMap` with a `Basemap.Type.OPEN_STREET_MAP` and add it to a `MapView`. The attribution text that is required by OpenStreetMap is automatically added to the `MapView's` attributio
This is always shown as a list for Java SE. Make this a two step list with the first step to create the map and the second to set it to the map view. The part about the attribution can be omitted.

2018-09-24 07:27 UTC, tschie commented on src/main/java/com/esri/samples/ogc/open_street_map_layer/README.md
> +## Relevant API
Add `Basemap.Type`

2018-09-24 07:27 UTC, tschie commented on src/main/java/com/esri/samples/ogc/open_street_map_layer/README.md
> +Layers
Add OpenStreetMap

2018-09-25 06:25 UTC, tschie commented on src/main/java/com/esri/samples/ogc/open_street_map_layer/README.md
> +<figcaption>OpenStreetMap Layer App</figcaption>
Don't need the `figcaption` or `figure`. I also don't think the renderer in the sample viewer will handle it.

2018-09-27 13:53 UTC, tschie commented on src/main/java/com/esri/samples/ogc/open_street_map_layer/OpenStreetMapLayerSample.java
> +      // create a map with an OpenSteetMap basemap
typo Steet

2018-10-03 10:44 UTC, tschie commented on src/main/java/com/esri/samples/ogc/open_street_map_layer/README.md
> +<h4>Tags</h4>
use h2 tag here

2018-10-03 10:44 UTC, tschie approved these changes
Looks good! Only one more thing to change (the `h2` tag in the readme). Feel free to merge after that.

2018-10-04 23:57 UTC, merged