display kml network links sample
Esri/arcgis-maps-sdk-java-samples pull request #276
Opened 2018-09-24 11:38 UTC by tschie

shows how to display KML that automatically updates and shows network messages

2018-09-24 14:07 UTC, tschie commented
I've asked why we only see two messages for this data. Will update when I find out

2018-09-24 14:26 UTC, colinanderson commented
I think you should only see one message with that data.

2018-09-26 09:58 UTC, tschie commented
Just re-ran this with the latest build and now I only see one message

2018-09-27 19:34 UTC, john0005 requested changes
A minor change.

2018-09-27 19:34 UTC, john0005 commented on src/main/java/com/esri/samples/ogc/display_kml_network_links/DisplayKMLNetworkLinksSample.java
> +      // add the KML layer as an operational layer and zoom to it after it is loaded
Would say, // add the KML layer as an operational layer and check if loaded correctly
This part has nothing to do with setting zoom

2018-09-27 19:34 UTC, john0005 commented on src/main/java/com/esri/samples/ogc/display_kml_network_links/README.md
> +    <li>Create a <code>KmlNetworkDataset</code> from a KML source which has network links.</li>
This should just be KmlDataset.

2018-09-28 08:59 UTC, merged