Open Mobile Scene Package
Esri/arcgis-maps-sdk-java-samples pull request #318
Opened 2019-02-15 11:35 UTC by Rachael-E

@tschie This PR into dev branch includes the implementation of the open mobile scene package scene for update 5. It also includes a data download path to AGOL in the build.gradle: however when this downloads, it is automatically unzipping it rather than coming in straight as a .mspk. I brought in the mspk file package on my computer via a different means to test the sample code (both with direct read and data which required unpacking), but we need to find a way to download the data directly from AGOL without it unzipping.

2019-02-18 12:20 UTC, Rachael-E commented
Update: got the .mspk download to work now: had uploaded the wrong type of file to AGOL.

2019-02-19 17:48 UTC, tschie requested changes
Looks good! Just some minor things

2019-02-19 17:48 UTC, tschie commented on src/main/java/com/esri/samples/scene/open_mobile_scene_package/OpenMobileScenePackageSample.java
> +        e.printStackTrace();
Should show an alert here with something like "mobile scene package direct read could not be determined"

2019-02-19 17:48 UTC, tschie commented on src/main/java/com/esri/samples/scene/open_mobile_scene_package/OpenMobileScenePackageSample.java
> +  public void loadMobileScenePackage(MobileScenePackage mobileScenePackage) {
this can be private

2019-02-19 17:48 UTC, tschie commented on src/main/java/com/esri/samples/scene/open_mobile_scene_package/OpenMobileScenePackageSample.java
> +    MobileScenePackage directReadMSPK = new MobileScenePackage(mspkPath);
move this to the line after `isDirectReadSupported.get()`

2019-02-19 17:48 UTC, tschie commented on src/main/java/com/esri/samples/scene/open_mobile_scene_package/OpenMobileScenePackageSample.java
> +    MobileScenePackage unpackedMSPK = new MobileScenePackage(tempUnpackedPath);
Move this and
```java
// create a temporary directory to store unpacked file if appropriate
Path tempDirectory = Files.createTempDirectory("offline_map");
final String tempUnpackedPath = tempDirectory.toString();
```

to the else branch below.

2019-02-19 17:48 UTC, tschie commented on src/main/java/com/esri/samples/scene/open_mobile_scene_package/OpenMobileScenePackageSample.java
> +
can remove this extra line

2019-02-19 17:48 UTC, tschie commented on src/main/java/com/esri/samples/scene/open_mobile_scene_package/README.md
> +1. Create a `String` pointing to the samples-data/mspk directory which hosts the .mspk data.
Once you move those lines into the if/else statement, I don't think you'll need this line. Plus this should be more general:
"Instantiate a `MobileScenePackage` with the path to the .mspk file", "Instantiate a `MobileScenePackage` with the path to the unpacked mspk".

2019-02-19 17:48 UTC, tschie commented on src/main/java/com/esri/samples/scene/open_mobile_scene_package/README.md
> +3. Instantiate two `MobileScenePackage` objects, one using the path to the local `.mspk` file and the other to the unpacked directory.
.mspk doesn't need code highlighting.

2019-02-19 17:48 UTC, tschie commented on src/main/java/com/esri/samples/scene/open_mobile_scene_package/README.md
> +4. Call `mobileScenePackage.loadAsync` and check for any errors.
Combine 4 and 5. Remove "check for any errors". These instructions should generally assume everything will work.

2019-02-19 17:48 UTC, tschie commented on src/main/java/com/esri/samples/scene/open_mobile_scene_package/README.md
> +5. When the mobile scene package is loaded, obtain the first `Scene` in the package using `mobileScenePackage.getScenes().get(0))`.
`ArcGISScene`

2019-02-19 17:48 UTC, tschie commented on src/main/java/com/esri/samples/scene/open_mobile_scene_package/README.md
> +5. When the mobile scene package is loaded, obtain the first `Scene` in the package using `mobileScenePackage.getScenes().get(0))`.
extra `)`

2019-02-19 17:48 UTC, tschie commented on src/main/java/com/esri/samples/scene/open_mobile_scene_package/README.md
> +6. Set the `SceneView` scene to the one obtained in the previous step.
In general, don't refer to previous steps. Maybe something like this:

5. Load the mobile scene package. When finished, get the `ArcGISScene` objects inside with `mobileScenePackage.getScenes()`.
6. Set the first scene in the collection on the scene view with `sceneView.setArcGISScene(scene)`.

2019-02-19 17:48 UTC, tschie commented on src/main/java/com/esri/samples/scene/open_mobile_scene_package/README.md
> +Read more about how to set up the sample's offline data [here](http://links.esri.com/ArcGISRuntimeQtSamples).
This whole section looks like it only applies to Qt...

2019-02-19 17:48 UTC, tschie commented on src/main/java/com/esri/samples/scene/open_mobile_scene_package/README.md
> +- Scene
Can remove Scene and SceneView

2019-02-20 11:10 UTC, Rachael-E commented
@tschie thanks for the review! I've made the changes: could you take another look please? Thanks.

2019-02-20 17:26 UTC, tschie approved these changes

2019-02-20 17:53 UTC, merged