Load WFS with XML query sample
Esri/arcgis-maps-sdk-java-samples pull request #335
Opened 2019-04-08 13:44 UTC by Rachael-E

The next WFS sample ready to review please @tschie, thanks!

2019-04-16 16:45 UTC, tschie requested changes
Mostly minor updates needed. The main one that needs fixing is the use of a raw XML string in code.

2019-04-16 16:45 UTC, tschie commented on src/main/java/com/esri/samples/ogc/wfs_xml_query/README.md
> +<li>Call <code>populateFromServiceAsync</code> to populate the table with only those features returned by the XML query.</li>
Call `populateFromServiceAsync` on the feature table...

2019-04-16 16:45 UTC, tschie commented on src/main/java/com/esri/samples/ogc/wfs_xml_query/README.md
> +<li>WfsFeatureTable.PopulateFromServiceAsync</li>
no methods

2019-04-16 16:45 UTC, tschie commented on src/main/java/com/esri/samples/ogc/wfs_xml_query/WfsXmlQuerySample.java
> +package com.esri.samples.ogc.wfs_xml_query;
missing copyright

2019-04-16 16:45 UTC, tschie commented on src/main/java/com/esri/samples/ogc/wfs_xml_query/WfsXmlQuerySample.java
> +    String serviceUrl = "https://dservices2.arcgis.com/ZQgQTuoyBrtmoGdP/arcgis/services/Seattle_Downtown_Features/WFSServer?service=wfs&request=getcapabilities";
don't need variables for these strings which are only used once

2019-04-16 16:45 UTC, tschie commented on src/main/java/com/esri/samples/ogc/wfs_xml_query/WfsXmlQuerySample.java
> +    String xmlQuery = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
😱 we should read the from a separate file or build the XML programatically...

2019-04-16 16:45 UTC, tschie commented on src/main/java/com/esri/samples/ogc/wfs_xml_query/WfsXmlQuerySample.java
> +    String xmlQuery = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
To read from a file, put the xml in the resources directory and read it with

```java
String xmlQuery = IOUtils.toString(WfsXmlQuerySample.class.getResourceAsStream("/xml/Query.xml"), StandardCharsets.UTF_8.name());
```

2019-04-16 16:45 UTC, tschie commented on src/main/java/com/esri/samples/ogc/wfs_xml_query/WfsXmlQuerySample.java
> +      try {
don't need this try/catch since you're not calling `get` on the future.

2019-04-16 16:45 UTC, tschie commented on src/main/java/com/esri/samples/ogc/wfs_xml_query/WfsXmlQuerySample.java
> +    ListenableFuture<FeatureQueryResult> featureQueryResultListenableFuture = wfsFeatureTable.populateFromServiceAsync(xmlQuery, true);
Don't need a variable for this since you don't use it later. Just call `wfsFeatureTable.populateFromServiceAsync(xmlQuery, true).addDoneListener...`

2019-04-16 16:45 UTC, tschie commented on src/main/java/com/esri/samples/ogc/wfs_xml_query/WfsXmlQuerySample.java
> +    // release resources when the application closes
this is redundant with the javadoc

2019-04-17 11:19 UTC, Rachael-E commented
thanks @tschie. I've added an xml file into resources to avoid using raw XML in the code. Can you take another look please?

2019-04-17 22:05 UTC, tschie commented
I think you missed the `<?xml version="1.0" encoding="UTF-8"?>` line at the top of the file. It's usually optional but it's good practice to include it.

2019-04-17 22:06 UTC, tschie approved these changes

2019-04-18 14:01 UTC, merged