Browse wfs layers
Esri/arcgis-maps-sdk-java-samples pull request #336
Opened 2019-04-11 11:25 UTC by Rachael-E

hey @tschie, here's the final WFS sample for U5, Browse WFS Layers. Can you review please? Thanks!

2019-04-16 16:49 UTC, tschie commented on src/main/java/com/esri/samples/ogc/browse_wfs_layers/BrowseWfsLayersSample.java
> +package com.esri.samples.ogc.browse_wfs_layers;
missing copyright

2019-04-16 17:11 UTC, tschie requested changes
A few minor changes needed and a few questions. I noticed some of the layers don't show anything when Swap coordinate order is checked. Is there a programmatic way to determine if that is going to happen? We might want some way to tell the user why nothing appears...

2019-04-16 17:11 UTC, tschie commented on src/main/java/com/esri/samples/ogc/browse_wfs_layers/BrowseWfsLayersSample.java
> +    Button loadButton = new Button("Load selected layer");
Do we need a button? Why not display the layer when the selected item is changed?

2019-04-16 17:11 UTC, tschie commented on src/main/java/com/esri/samples/ogc/browse_wfs_layers/README.md
> +# Browse WFS layers
Needs to be HTML

2019-04-16 17:11 UTC, tschie commented on src/main/java/com/esri/samples/ogc/browse_wfs_layers/BrowseWfsLayersSample.java
> +  private Renderer getRandomRendererForTable (WfsFeatureTable table) {
I don't like this. It's very easy to get randomly generated ugly colors. We should hardcode good looking colors.

2019-04-16 17:11 UTC, tschie commented on src/main/java/com/esri/samples/ogc/browse_wfs_layers/BrowseWfsLayersSample.java
> +    if (table.getGeometryType() == GeometryType.POINT || table.getGeometryType() == GeometryType.MULTIPOINT){
A switch statement should be used here.

2019-04-16 17:11 UTC, tschie commented on src/main/java/com/esri/samples/ogc/browse_wfs_layers/BrowseWfsLayersSample.java
> +        for (WfsLayerInfo layerInfo : wfsLayerInfos) {
replace for loop with `wfsLayerNamesListView.getItems().addAll(wfsLayerInfos);`

2019-04-16 17:11 UTC, tschie commented on src/main/java/com/esri/samples/ogc/browse_wfs_layers/BrowseWfsLayersSample.java
> +    wfsService.addDoneLoadingListener(() -> {
add some comment about browsing the layers in the service since that is the main point of the sample

2019-04-16 17:11 UTC, tschie commented on src/main/java/com/esri/samples/ogc/browse_wfs_layers/BrowseWfsLayersSample.java
> +    ListenableFuture<FeatureQueryResult> featureQueryResultListenableFuture = wfsFeatureTable.populateFromServiceAsync(new QueryParameters(), false, null );
Don't need a variable here since you're not using it. Just chain `addDoneListener` on the end of `populateFromServiceAsync`.

2019-04-16 17:11 UTC, tschie commented on src/main/java/com/esri/samples/ogc/browse_wfs_layers/BrowseWfsLayersSample.java
> +    wfsFeatureTable.setFeatureRequestMode(ServiceFeatureTable.FeatureRequestMode.MANUAL_CACHE);
Should this line go closer to the `populateFromServiceAsync` line?

2019-04-16 17:11 UTC, tschie commented on src/main/java/com/esri/samples/ogc/browse_wfs_layers/BrowseWfsLayersSample.java
> +    wfsFeatureTable.setAxisOrder(checkBox.isSelected() ? OgcAxisOrder.SWAP : OgcAxisOrder.NO_SWAP);
Add a comment for this line explaining what this is

2019-04-16 17:11 UTC, tschie commented on src/main/java/com/esri/samples/ogc/browse_wfs_layers/BrowseWfsLayersSample.java
> +    // clear existing WFSLayerInfos from the map's operational layers
looks like you're clearing layers

2019-04-17 11:43 UTC, Rachael-E commented on src/main/java/com/esri/samples/ogc/browse_wfs_layers/BrowseWfsLayersSample.java
> +    Button loadButton = new Button("Load selected layer");
agreed, will update. We'll have parity with Android implementation that way.

2019-04-18 13:55 UTC, Rachael-E commented
@tschie thanks for the constructive review: I've addressed your comments. Please can you take another look?

2019-04-19 15:52 UTC, tschie commented on src/main/java/com/esri/samples/ogc/browse_wfs_layers/BrowseWfsLayersSample.java
> +    checkBox.setOnAction(event -> {
you can omit the braces `{` for single line lamdas. Your IDE should hint this if your language level is set to 11.

2019-04-19 15:53 UTC, tschie commented on src/main/java/com/esri/samples/ogc/browse_wfs_layers/BrowseWfsLayersSample.java
> +    Label label = new Label("Data in this sample doesn't require coord swapping to display. Uncheck to display data.");
I didn't realize all of the layers don't require it. In that case, I think this option should be removed. What's the point of having it in the sample if it's not being demonstrated? This should be brought up with the team.

2019-04-23 14:43 UTC, Rachael-E commented
@tschie I've removed the checkbox from the sample, Lucas was in agreement it just adds confusion. Can this be merged now?

2019-04-25 17:20 UTC, tschie approved these changes

2019-04-25 17:23 UTC, merged