Token authentication
Esri/arcgis-maps-sdk-java-samples pull request #347
Opened 2019-05-10 14:21 UTC by JonLavi

Hi @Rachael-E , another small sample to look over. Thanks! 
@DonMoJa you could use this readme for your refactoring.

2019-05-10 17:28 UTC, Rachael-E requested changes
Nice work! Just some minor tidying up to do throughout, and rephrasing for the Readme.

2019-05-10 17:28 UTC, Rachael-E commented on src/main/java/com/esri/samples/portal/token_authentication/README.md
> +<p>access a map service that is secured with ArcGIS token-based authentication</p>
typo: capitalize access

add "an" in front of ArcGIS
full stop at end of description

2019-05-10 17:28 UTC, Rachael-E commented on src/main/java/com/esri/samples/portal/token_authentication/README.md
> +<h2>Relevant API</h2>
This list should be in alphabetical order

2019-05-10 17:28 UTC, Rachael-E commented on src/main/java/com/esri/samples/portal/token_authentication/TokenAuthenticationSample.java
> +      stage.setTitle("Display Map Sample");
oops: update to "Token Authentication Sample" ;)

2019-05-10 17:28 UTC, Rachael-E commented on src/main/java/com/esri/samples/portal/token_authentication/TokenAuthenticationSample.java
> +      stackPane.getChildren().addAll(mapView);
since you're only adding one item to the stack pane here, you can use

`stackPane.getChildren().add(mapView)`

2019-05-10 17:28 UTC, Rachael-E commented on src/main/java/com/esri/samples/portal/token_authentication/TokenAuthenticationSample.java
> +    } catch (Exception e) {
add a new line above catch for readability

2019-05-10 17:28 UTC, Rachael-E commented on src/main/java/com/esri/samples/portal/token_authentication/TokenAuthenticationSample.java
> +
remove additional empty line between braces

2019-05-10 17:28 UTC, Rachael-E commented on src/main/java/com/esri/samples/portal/token_authentication/README.md
> +<p>When starting the sample, the user is presented with an authentication dialog for the ArcGIS Online map server. Upon successful authentication, access to the map server is granted and the data is
this section was recently refactored for the same sample on the Android Repo, I've made some edits to this section based on that.

"When starting the sample, the user is challenged for an ArcGIS Online login to view the protected map service. Enter a username and password for an ArcGIS Online named user account (such as your ArcGIS for Developers account). Upon successful authentication, the protected map service will display in the map."

2019-05-10 17:28 UTC, Rachael-E commented on src/main/java/com/esri/samples/portal/token_authentication/README.md
> +  <li>Create a <code>PortalItem</code> for the protected web map using the <code>Portal</code> and Item ID of the protected map service.</li>
"....and Item ID of the protected map service as parameters".

2019-05-10 17:28 UTC, Rachael-E commented on src/main/java/com/esri/samples/portal/token_authentication/README.md
> +  <li>Create a map to display in the <code>MapView</code> using the <code>PortalItem</code>.</li>
"Create an <code>ArcGISMap</code> from the portal item, and display it in a <code>MapView</code>."

2019-05-10 17:28 UTC, Rachael-E commented on src/main/java/com/esri/samples/portal/token_authentication/README.md
> +  <li>Set the map to display in the <code>MapView</code>.</li>
because you've already phrased map view as an object `MapView` in the previous line, you can just refer to it as "map view" here.

2019-05-13 08:33 UTC, JonLavi commented on src/main/java/com/esri/samples/portal/token_authentication/TokenAuthenticationSample.java
> +      stage.setTitle("Display Map Sample");
Totally busted!

2019-05-13 15:34 UTC, colinanderson approved these changes
@JonLavi looks ok.

2019-05-14 08:48 UTC, Rachael-E approved these changes
Good changes, nice one! Approved to merge now.

2019-05-14 09:05 UTC, merged