Update readmes to match common design (Display Information category) 2/2
Esri/arcgis-maps-sdk-java-samples pull request #448
Opened 2020-03-11 20:21 UTC by JonLavi

2020-03-17 19:00 UTC, Rachael-E requested changes
@JonLavi all good bar one how it works section: I've left some comments there, thanks

2020-03-17 19:00 UTC, Rachael-E commented on display_information/control-annotation-sublayer-visibility/README.md
> +2. Populate checkbox text with the `AnnotationSublayer` names (including maximum and minimum scales, where relevant).
this whole how it works section isn't consistent with our other how it works sections :( it focusses on UI and not the API development workflow. It's unlikely this would go through a re-review in common samples. For Java we should at least pepper through some of the logic code for this if you don't feel comfortable restructuring this.  There are things I would remove though, such as the level of detail for changing the text to black and light gray: this is not something we should be setting out in the How it Works section since it has nothing to do with our API.

2020-03-25 10:33 UTC, JonLavi commented on display_information/control-annotation-sublayer-visibility/README.md
> +2. Populate checkbox text with the `AnnotationSublayer` names (including maximum and minimum scales, where relevant).
Totally agree @Rachael-E . I've revamped with a suggestion. Can you let me know what you think? Cheers!

2020-03-25 11:34 UTC, Rachael-E approved these changes
cool, looks good thanks!

2020-03-27 09:33 UTC, merged