Update Local Server readme instructions
Esri/arcgis-maps-sdk-java-samples pull request #627
Opened 2021-03-22 18:08 UTC by Rachael-E

### Description

This PR updates the Local Server sample readmes with instructions of how to manually switch the install version of Local Server that the samples access. 

This is important for our release of the 100.10.0 sample viewer, as Runtime 100.10.0 shipped with setting an environment variable for a Local Server version of 100.10, whereas the most up to date version of Local Server is 100.9: API v100.10.0 will not find the correct install path for Local Server 100.9.0 as it is currently configured. This is also useful information for a user to have if they wish to switch Local Server versions in the future. 

@mbcoder could you take a look please?

2021-03-23 14:23 UTC, mbcoder approved these changes
Looks good as discussed earlier

2021-03-23 18:09 UTC, mbranscomb requested changes
Made some suggestions.

2021-03-23 18:09 UTC, mbranscomb commented on local_server/local-server-feature-layer/README.md
> +    1. Create a `ServiceFeatureTable(Url)` from local feature service url provided by `LocalFeatureService.getUrl()`.
This may need layer ID as well?

2021-03-23 18:09 UTC, mbranscomb commented on local_server/local-server-feature-layer/README.md
> +    2. Load the table asynchronously using `ServiceFeatureTable.loadAsync()`.
After loading a table, we recommend checking for load errors.

2021-03-23 18:09 UTC, mbranscomb commented on local_server/local-server-feature-layer/README.md
> +Note: You may wish to reference earlier releases of Local Server. For example, the ArcGIS Runtime API for Java v100.10.0 is configured for Local Server v100.10.0. If you wish to access Local Server 1
Specific versions of ArcGIS Runtime Local Server are compatible with the version of ArcGIS Pro you use to create geoprocessing and map packages. For example, the ArcGIS Runtime API for Java v100.10.0 is configured for Local Server v100.10.0 which provides compatibility for packages created with ArcGIS Pro 2.7.x. For more information see https://developers.arcgis.com/java/reference/system-requirements/#local-server-version-compatibility-with-arcgis-desktop-and-arcgis-pro.
To configure the ArcGIS Runtime API for Java v100.10.0 to work with Local Server 100.9.0:
- Development machine: 
  - Locate the Local Server installation directory and rename the folder from `LocalServer100.9` to `LocalServer100.10`.
  - Update the environment variable from `RUNTIME_LOCAL_SERVER_100_9` to `RUNTIME_LOCAL_SERVER_100_10`.
- Deployment machine(s): Rename the deployment folder included with your application (or referenced by the LocalServerEnvironment.InstallPath property) from `LocalServer100.9` to `LocalServer100.10`.

2021-03-23 18:09 UTC, mbranscomb commented on local_server/local-server-geoprocessing/README.md
> +Note: You may wish to reference earlier releases of Local Server. For example, the ArcGIS Runtime API for Java v100.10.0 is configured for Local Server v100.10.0. If you wish to access Local Server 1
See alternative suggestion above.

2021-03-23 18:09 UTC, mbranscomb commented on local_server/local-server-map-image-layer/README.md
> +Note: You may wish to reference earlier releases of Local Server. For example, the ArcGIS Runtime API for Java v100.10.0 is configured for Local Server v100.10.0. If you wish to access Local Server 1
See alternative suggestion above.

2021-03-23 18:09 UTC, mbranscomb commented on local_server/local-server-services/README.md
> +Note: You may wish to reference earlier releases of Local Server. For example, the ArcGIS Runtime API for Java v100.10.0 is configured for Local Server v100.10.0. If you wish to access Local Server 1
See alternative suggestion above.

2021-03-24 11:25 UTC, Rachael-E commented on local_server/local-server-feature-layer/README.md
> +    1. Create a `ServiceFeatureTable(Url)` from local feature service url provided by `LocalFeatureService.getUrl()`.
looks like this is covered already in the code: for the readmes we go for a higher level description and leave the details in the code/code comments.

2021-03-24 11:31 UTC, Rachael-E commented on local_server/local-server-feature-layer/README.md
> +    2. Load the table asynchronously using `ServiceFeatureTable.loadAsync()`.
as above, we tend not to go into this much detail in the readmes and provide an overview of the main steps. We handle error checking in the sample code.

2021-03-24 14:47 UTC, merged