[New sample] Display content of utility network container
Esri/arcgis-maps-sdk-java-samples pull request #664
Opened 2021-09-24 14:40 UTC by Rachael-E

This PR is for a new utility network sample (U10 functionality) for Display content of utility network container. @jenmerritt could you take a first review please?

2021-09-29 15:49 UTC, jenmerritt reviewed
@Rachael-E Looks good overall, reads and works well. Just a few comments and thoughts to consider.

2021-09-29 15:49 UTC, jenmerritt commented on utility_network/display-content-of-utility-network-container/README.md
> +1. Load a web map that include ArcGIS Pro [Subtype Group Layers](https://pro.arcgis.com/en/pro-app/help/mapping/layer-properties/subtype-layers.htm) with only container features visible (i.e. fuse ba
```suggestion
1. Load a web map that include ArcGIS Pro [Subtype Group Layers](https://pro.arcgis.com/en/pro-app/help/mapping/layer-properties/subtype-layers.htm) with only container features visible (i.e. fuse bank, switch bank, transformer bank, hand hole and junction box).
```
a web map that includes / web maps that include

2021-09-29 15:49 UTC, jenmerritt commented on utility_network/display-content-of-utility-network-container/README.md
> +11. Get associations for this extent using `getAssociationsAsync(Envelope)`
```suggestion
11. Get associations for this extent using `getAssociationsAsync(Envelope)`.
```

2021-09-29 15:49 UTC, jenmerritt commented on utility_network/display-content-of-utility-network-container/README.md
> +13. Turn on the visibility of all the map's operational layers, clear the graphics in the graphics overlay, and zoom out to previous extent to exit container view.
```suggestion
13. Turn on the visibility of all the map's operational layers, clear the graphics in the graphics overlay, and zoom out to the previous extent to exit the container view.
```

2021-09-29 15:49 UTC, jenmerritt commented on utility_network/display-content-of-utility-network-container/src/main/java/com/esri/samples/display_content_of_utility_network_container/DisplayContentOfUtilityNetworkContainerController.java
> +import com.esri.arcgisruntime.loadable.LoadStatus;
```suggestion
import com.esri.arcgisruntime.loadable.LoadStatus;
```
ctrl+alt+o on your imports to tidy the order

2021-09-29 15:49 UTC, jenmerritt commented on utility_network/display-content-of-utility-network-container/src/main/java/com/esri/samples/display_content_of_utility_network_container/DisplayContentOfUtilityNetworkContainerController.java
> +                if (contentElements.size() > 0) {
could use `isEmpty()` here

2021-09-29 15:49 UTC, jenmerritt commented on utility_network/display-content-of-utility-network-container/src/main/java/com/esri/samples/display_content_of_utility_network_container/DisplayContentOfUtilityNetworkContainerController.java
> +  }
```suggestion
      });
    }
  }
```
Could lose a few line spaces here

2021-09-29 15:49 UTC, jenmerritt commented on utility_network/display-content-of-utility-network-container/src/main/java/com/esri/samples/display_content_of_utility_network_container/DisplayContentOfUtilityNetworkContainerController.java
> +    mapView.setViewpointGeometryAsync(GeometryEngine.buffer(graphicsOverlay.getExtent(), 0.05));
Maybe add a comment here?

2021-09-29 15:49 UTC, jenmerritt commented on utility_network/display-content-of-utility-network-container/src/main/java/com/esri/samples/display_content_of_utility_network_container/DisplayContentOfUtilityNetworkContainerController.java
> +    ListenableFuture<List<UtilityAssociation>> extentAssociations = utilityNetwork.getAssociationsAsync(graphicsOverlay.getExtent());
You call `graphicsOverlay.getExtent()` twice in this method so could consider creating a variable to reuse.

2021-09-29 15:49 UTC, jenmerritt commented on utility_network/display-content-of-utility-network-container/src/main/java/com/esri/samples/display_content_of_utility_network_container/DisplayContentOfUtilityNetworkContainerController.java
> +
```suggestion
```

2021-09-29 15:49 UTC, jenmerritt commented on utility_network/display-content-of-utility-network-container/src/main/java/com/esri/samples/display_content_of_utility_network_container/DisplayContentOfUtilityNetworkContainerController.java
> +            UtilityElement containerElement = utilityNetwork.createElement(selectedContainerFeature);
Is there a risk here that `selectedContainedFeature` is null if no results/features are found in the query? e.g. if lines 157/158 don't happen. There maybe isn't that risk with the dataset being used. 

I forced it and you basically get an IllegalArgumentException which isn't handled in that try/catch (only Interuppted/Execution exceptions on line 242)

2021-09-30 14:20 UTC, jenmerritt approved these changes
@Rachael-E  Approving based on our discussion / to allow to move to second review while I'm away

2021-10-07 13:47 UTC, mbcoder requested changes
Looks okay.  Some minor comments some of which you can choose to address in a different PR.

handleMapViewClicked is quite big, but once you read it, it makes sense.

2021-10-07 13:47 UTC, mbcoder commented on utility_network/display-content-of-utility-network-container/build.gradle
> +    id 'org.openjfx.javafxplugin' version '0.0.8'
There is a newer version of the plugin.  Appreciate you might not want to update this for this sample alone.

2021-10-07 13:47 UTC, mbcoder commented on utility_network/display-content-of-utility-network-container/build.gradle
> +    gradleVersion = '7.0.2'
Current gradle version is 7.2 

Appreciate you might not want to change this as part of this sample alone

2021-10-07 13:47 UTC, mbcoder commented on utility_network/display-content-of-utility-network-container/src/main/java/com/esri/samples/display_content_of_utility_network_container/DisplayContentOfUtilityNetworkContainerLauncher.java
> + * Wrapper required for launching a JavaFX 11 app through Gradle or from a jar.
Consider not saying JavaFX 11.  Very soon it will be Java 17 too.  The Java / JavaFX versions are listed in the System Requirements, so not listing it here saves updating all sample in future.

2021-10-07 13:47 UTC, mbcoder commented on utility_network/display-content-of-utility-network-container/src/main/java/com/esri/samples/display_content_of_utility_network_container/DisplayContentOfUtilityNetworkContainerController.java
> +//    Envelope graphicsOverlayExtent = graphicsOverlay.getExtent();
Commented out code?

2021-10-07 13:47 UTC, mbcoder commented on utility_network/display-content-of-utility-network-container/src/main/java/com/esri/samples/display_content_of_utility_network_container/DisplayContentOfUtilityNetworkContainerController.java
> +  public void initialize() {
Missing JavaDoc for init method

2021-10-07 15:01 UTC, Rachael-E commented on utility_network/display-content-of-utility-network-container/build.gradle
> +    id 'org.openjfx.javafxplugin' version '0.0.8'
as discussed, we'll do these updates as a batch for all samples in the future 👍

2021-10-07 15:01 UTC, Rachael-E commented on utility_network/display-content-of-utility-network-container/src/main/java/com/esri/samples/display_content_of_utility_network_container/DisplayContentOfUtilityNetworkContainerLauncher.java
> + * Wrapper required for launching a JavaFX 11 app through Gradle or from a jar.
as above: this can be done as a batch when we upgrade to Java 17

2021-10-07 15:30 UTC, merged