New Local Server Services
Esri/arcgis-maps-sdk-java-samples pull request #75
Opened 2016-10-07 10:13 UTC by john0005

Almost ready to merge.

Taking over for this PR: https://github.com/Esri/arcgis-runtime-samples-java/pull/66

2016-10-07 10:15 UTC, john0005 commented on src/main/java/com/esri/samples/localserver/local_server_services/LocalServerServicesSample.java
> +    FXMLLoader loader = new FXMLLoader(getClass().getResource("/local_server/local_server_services.fxml"));
@tyle8552 In the other pull request you said we need to add these to Samples_data, is that an easy thing to do?

2016-10-07 10:15 UTC, john0005 commented on src/main/java/com/esri/samples/localserver/local_server_services/LocalServerServicesController.java
> +            serviceUrl = Paths.get(getClass().getResource("/local_server/PointsofInterest.mpk").toURI()).toString();
@tyle8552 In the other pull request you said we need to add these to Samples_data, is that an easy thing to do?

2016-10-07 22:19 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_services/LocalServerServicesController.java
> +            serviceUrl = Paths.get(getClass().getResource("/local_server/PointsofInterest.mpk").toURI()).toString();
@john0005 It's easy, but you have to be added to the org. I can put it up. Have to make sure it's approved for public use first. Do you know if it has already been approved?

2016-10-07 23:50 UTC, ghost requested changes
A few more comments. Also, can you change the images to be 800w x 400h like the other samples? That gif tool allows you to set specific dimensions.

Also, please remove the gpk and mpk files. I've added them to samples_data.

2016-10-07 23:50 UTC, ghost commented on src/main/java/com/esri/samples/localserver/local_server_services/LocalServerServicesController.java
> +  protected void handleStartLocalServer() {
make methods private. fxml annotation can still find them

2016-10-07 23:50 UTC, ghost commented on src/main/java/com/esri/samples/localserver/local_server_services/LocalServerServicesController.java
> +    server = LocalServer.INSTANCE;
should not look like we are reassigning a variable to a singleton. make `static final` and assign in declaration (line 51) OR assign in `initialize()` method without `final`.

2016-10-07 23:50 UTC, ghost commented on src/main/java/com/esri/samples/localserver/local_server_services/README.md
> +<p><img src="LocalServerServices.gif" alt="" title="" /></p>
Move img to between first p tag and How to use the sample (line 4). Also remove alt tag and put title="LocalServerServices"

2016-10-07 23:50 UTC, ghost commented on src/main/java/com/esri/samples/localserver/local_server_services/README.md
> +<p>Text Area (Middle):
Close p tag on this line. Put list items in an unordered list so the list is shown indented after the colon.

2016-10-07 23:50 UTC, ghost commented on src/main/java/com/esri/samples/localserver/local_server_services/README.md
> +<h2>Tags</h2>
Sorry, we've gone back to Features ;)

2016-10-07 23:50 UTC, ghost commented on src/main/java/com/esri/samples/localserver/local_server_services/LocalServerServicesController.java
> +   * @param event the event that fired this action
no param event

2016-10-07 23:50 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_services/LocalServerServicesController.java
> +    int listIndex = runningServices.getSelectionModel().getSelectedIndex();
Move to initialize:
```java
btnStopService.disableProperty().bind(runningServices.getSelectionModel().selectedIndexProperty().isNotEqualTo(-1));
btnUrl.disableProperty().bind(btnStopService.disableProperty());
```

Try to use property binding when possible.

2016-10-07 23:50 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_services/LocalServerServicesController.java
> +  protected void handleURL(ActionEvent event) {
Parameter `event` is not used, so you can remove it.

2016-10-07 23:50 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_services/LocalServerServicesController.java
> +    if (server != null && server.getStatus() == LocalServerStatus.STARTED) {
Move this logic to `handleStopLocalServer` and call it from `terminate` since this logic is actually doing the stopping.

2016-10-07 23:50 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_services/LocalServerServicesController.java
> +    btnStartServer.setDisable(true);
probably a neater way to do it with a property, but not crucial

2016-10-07 23:50 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_services/LocalServerServicesController.java
> +  protected void handleStartLocalService(ActionEvent event) throws URISyntaxException {
event param not used

2016-10-07 23:50 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_services/LocalServerServicesController.java
> +            serviceUrl = Paths.get(getClass().getResource("/local_server/PointsofInterest.mpk").toURI()).toString();
I've added them. Delete your samples_data folder and refresh the project to download the new data. Make sure this data is approved for public use.

2016-10-07 23:50 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_services/LocalServerServicesController.java
> +  protected void handleStopLocalService(ActionEvent event) {
param event not used

2016-10-12 07:33 UTC, john0005 commented on src/main/resources/local_server/local_server_services.fxml
> +            btnStopService.disableProperty().bind(runningServices.getSelectionModel().selectedIndexProperty().isEqualTo(-1));
@tyle8552 What do you think about this? I am trying to handle the button disable binding in FXML instead of the java code.

This way I can just get rid of the method to enable/disable buttons.

2016-10-13 15:58 UTC, tyle8552 commented on src/main/resources/local_server/local_server_services.fxml
> +            btnStopService.disableProperty().bind(runningServices.getSelectionModel().selectedIndexProperty().isEqualTo(-1));
I would put that line in the controller initialize() method along with any other more complex property bindings.

2016-10-13 17:57 UTC, ghost approved these changes

2016-10-13 18:01 UTC, merged