Update samples to use Color class
Esri/arcgis-maps-sdk-java-samples pull request #761
Opened 2022-11-17 18:54 UTC by Luiy0

### Description

The following changes were made to samples where applicable:

- Remove unused imports.
- Remove code marked for deprecation related to the use of `Color`.
- Remove the `controls` module requirement in samples that do not use or need it.

Checklist:
- [ ] Set target branch to main (current release) or v.next (next release)
- [ ] Request a reviewer
- [ ] Assign a reviewer
- [ ] Tag reviewer in comment

2022-11-18 10:52 UTC, Luiy0 commented
Hi @Rachael-E, this one's ready for a first review, thanks.

2022-11-21 13:56 UTC, Rachael-E requested changes
@Luiy0 thanks, lots of really great changes here that improve our samples readability so much. Just a couple of comments here, mostly regarding existing code in the samples that we can take the opportunity to improve fairly easily.

2022-11-21 13:56 UTC, Rachael-E commented on geometry/convex-hull-list/src/main/java/com/esri/samples/convex_hull_list/ConvexHullListSample.java
> +          SimpleFillSymbol convexHullFill = new SimpleFillSymbol(SimpleFillSymbol.Style.NULL, Color.TRANSPARENT, convexHullLine);
hmm this has raised a clean up we can use: if the style is null, and the color is transparent, then the sample isn't showing any fill. In the samples case, we just need to see an outline of the convex hull. We can tidy this sample instead by only using the SimpleLineSymbol:

```java
Graphic convexHullGraphic = new Graphic(geometry, convexHullLine);
```

2022-11-21 13:56 UTC, Rachael-E commented on geometry/convex-hull/src/main/java/com/esri/samples/convex_hull/ConvexHullSample.java
> +      SimpleFillSymbol fillSymbol = new SimpleFillSymbol(SimpleFillSymbol.Style.NULL, Color.TRANSPARENT, lineSymbol);
same comment here as before, we don't need this fill (consider convex hull operation as draping a rubber band around points. We have other samples that show how to apply a simple marker symbol too)

```java
          case POLYLINE:
          case POLYGON:
            convexHullGraphic.setSymbol(lineSymbol);
            break;

```

2022-11-21 13:56 UTC, Rachael-E commented on geometry/geodesic-sector-and-ellipse/src/main/java/com/esri/samples/geodesic_sector_and_ellipse/GeodesicSectorAndEllipseController.java
> +    sectorFillSymbol = new SimpleFillSymbol(SimpleFillSymbol.Style.SOLID, Color.web("lime", 0.8), null);
for readability and reduced repetition, let's use a local variable to store the lime color

```java
    Color transparentLime = Color.web("lime", 0.8);
    sectorFillSymbol = new SimpleFillSymbol(SimpleFillSymbol.Style.SOLID, transparentLime, null);
    sectorLineSymbol = new SimpleLineSymbol(SimpleLineSymbol.Style.SOLID, transparentLime, 3);
    sectorMarkerSymbol = new SimpleMarkerSymbol(SimpleMarkerSymbol.Style.CIRCLE, transparentLime, 3);

```

2022-11-21 13:56 UTC, Rachael-E commented on geometry/geodesic-sector-and-ellipse/src/main/java/com/esri/samples/geodesic_sector_and_ellipse/GeodesicSectorAndEllipseController.java
>      // create a red dotted outline graph for showing the geodesic ellipse geometry
```suggestion
    // create a red dotted outline graphic for showing the geodesic ellipse geometry
```

2022-11-21 13:56 UTC, Rachael-E commented on kml/create-and-save-kml-file/src/main/java/com/esri/samples/create_and_save_kml_file/CreateAndSaveKMLFileController.java
> +            KmlLineStyle kmlLineStyle = new KmlLineStyle(polylineColor, 8);
```suggestion
            var kmlLineStyle = new KmlLineStyle(polylineColor, 8);
```

2022-11-21 13:56 UTC, Rachael-E commented on kml/create-and-save-kml-file/src/main/java/com/esri/samples/create_and_save_kml_file/CreateAndSaveKMLFileController.java
> +            KmlPolygonStyle kmlPolygonStyle = new KmlPolygonStyle(polygonColor);
```suggestion
            var kmlPolygonStyle = new KmlPolygonStyle(polygonColor);
```

2022-11-21 14:00 UTC, Rachael-E reviewed
@Luiy0 I did a search for "0x" in IntelliJ for the .java classes and found a couple more references to the old color codes that should be tidied up in this PR. Example of one here: most are in comments, see screenshot below. Thanks! 
 
![Screenshot 2022-11-21 at 14 00 23](https://user-images.githubusercontent.com/36415565/203073735-cc9ab4cb-16ba-41bf-b6ac-8df4a2a09a7c.png)

2022-11-21 14:00 UTC, Rachael-E commented on geometry/geometry-engine-simplify/src/main/java/com/esri/samples/geometry_engine_simplify/GeometryEngineSimplifySample.java
>      // transparent (0x00000000) fill
```suggestion
    // transparent fill
```

2022-11-22 14:48 UTC, Rachael-E approved these changes
looks good @Luiy0 thanks! tiny suggestion then good for second review.

2022-11-22 14:48 UTC, Rachael-E commented on network_analysis/closest-facility-static/src/main/java/com/esri/samples/closest_facility_static/ClosestFacilityStaticSample.java
> +      SimpleLineSymbol simpleLineSymbol = new SimpleLineSymbol(SimpleLineSymbol.Style.SOLID, Color.web("blue", 0.4), 5.0f);
```suggestion
      var simpleLineSymbol = new SimpleLineSymbol(SimpleLineSymbol.Style.SOLID, Color.web("blue", 0.4), 5.0f);
```

2022-11-23 10:28 UTC, Luiy0 commented
Ready for a second review @jenmerritt, thanks.

2022-11-23 11:28 UTC, jenmerritt approved these changes
Wow, ok I think this is fine. Couple of import expansions but approving.

2022-11-23 11:28 UTC, jenmerritt commented on geometry/geodesic-operations/src/main/java/com/esri/samples/geodesic_operations/GeodesicOperationsSample.java
>  import javafx.scene.layout.*;
Could clean this `*`

2022-11-23 11:28 UTC, jenmerritt commented on kml/create-and-save-kml-file/src/main/java/com/esri/samples/create_and_save_kml_file/CreateAndSaveKMLFileController.java
>  import com.esri.arcgisruntime.ogc.kml.*;
could tidy up this `*`

2022-11-23 12:36 UTC, merged