Testing loadStatus property 2
Esri/arcgis-maps-sdk-java-samples pull request #763
Opened 2022-11-23 14:00 UTC by Luiy0

### Description

- Remove deprecated code related to `loadStatus`.

Checklist:
- [ ] Set target branch to main (current release) or v.next (next release)
- [ ] Request a reviewer
- [ ] Assign a reviewer
- [ ] Tag reviewer in comment

2022-11-28 15:28 UTC, Luiy0 commented
Hi @Rachael-E, here's another set of samples ready for review. Thanks!

2022-11-30 15:06 UTC, Rachael-E requested changes
thanks @Luiy0 ! Another interesting case coming up here. I've left a couple of comments for the Browse WFS Layers sample, let me know if you'd like to talk over any of it.

2022-11-30 15:06 UTC, Rachael-E commented on ogc/browse-wfs-layers/src/main/java/com/esri/samples/browse_wfs_layers/BrowseWfsLayersSample.java
> +    progressIndicator.visibleProperty().bind(wfsFeatureTable.loadStatusProperty().isEqualTo(LoadStatus.LOADING));
This new bind is listening for the status of the load status on the wfsFeatureTable. In the original code, the progressIndicator visibility is being set to false when the **`populateFromServiceAsync()` listener** had completed. 

So in this case, this call isn't interchangeable since the listeners are handling two different things. Compare java doc e.g. [populateFromServiceAsync](https://developers.arcgis.com/java/api-reference/reference/com/esri/arcgisruntime/ogc/wfs/WfsFeatureTable.html#populateFromServiceAsync(com.esri.arcgisruntime.data.QueryParameters,boolean,java.lang.Iterable))

> Returns:
a ListenableFuture that represents the result of the query; the results will replace or be appended to this table. The ListenableFuture indicates if the query isDone(); also allows cancellation. Calling get() on the returned future may throw an ExecutionException with its cause set to [IOException](https://docs.oracle.com/javase/10/docs/api/java/io/IOException.html?is-external=true) if a network request fails. 


Let's keep the progress indicator code as it was, since we're listening for the populateFromServiceAsync status return rather than the loadStatus return.

```java

    wfsFeatureTable.populateFromServiceAsync(new QueryParameters(), false, null ).addDoneListener(()->{
      progressIndicator.setVisible(false);
      mapView.setViewpointGeometryAsync(wfsFeatureLayer.getFullExtent(), 50);
    });
```


Could we use a property for the code below, where the addDoneLoadingListener is called for the switch statements? Replacing the listener with the property?

2022-11-30 15:06 UTC, Rachael-E commented on ogc/browse-wfs-layers/src/main/java/com/esri/samples/browse_wfs_layers/BrowseWfsLayersSample.java
> +    progressIndicator.visibleProperty().bind(wfsFeatureTable.loadStatusProperty().isEqualTo(LoadStatus.LOADING));
I see with my above suggestion, the progressIndicator won't allow visibility changes due to the below which makes sense (and I think is the error you were running into?)

> ProgressIndicator.visible : A bound value cannot be set.

We have a couple of options here. 

1. Have two separate instances of the progress indicator, one for the loadStatus on the wfsService and another for the doneListener from the populateFromServiceAsync. 
2. Have the vBox disabled and show a message in it when the WFSService is loading. When it's finished loading, enable the vBox for user interaction. That means only then needing one ProgressIndicator to show the populateFromServiceAsync is querying (and disapppearing when done).

2022-12-01 13:03 UTC, Luiy0 commented on ogc/browse-wfs-layers/src/main/java/com/esri/samples/browse_wfs_layers/BrowseWfsLayersSample.java
> +    progressIndicator.visibleProperty().bind(wfsFeatureTable.loadStatusProperty().isEqualTo(LoadStatus.LOADING));
@Rachael-E Following from option 1, I've added another progress indicator that uses the `setVisible()` method. I'm not confident that replacing the `addDoneLoadingListener` will improve anything here for the switch. We would have to check if `newValue` is `LOADED` and then do the switch.

2022-12-02 11:26 UTC, Rachael-E approved these changes
thanks @Luiy0 looks good to me. ready for 2nd review!

2022-12-05 09:25 UTC, Luiy0 commented
Hi @jenmerritt, this one's ready for another look. Thanks.

2022-12-05 15:07 UTC, jenmerritt approved these changes
LGTM @Luiy0

2022-12-05 15:12 UTC, merged