Local Server Geoprocessing
Esri/arcgis-maps-sdk-java-samples pull request #78
Opened 2016-10-07 11:50 UTC by john0005

Status: not ready

taking over for PR: https://github.com/Esri/arcgis-runtime-samples-java/pull/72

2016-11-03 09:46 UTC, john0005 commented
@tyle8552 Can you look this over? May need to add RasterHill.tpk and Contour.gpk to samples-data.

2016-11-03 10:03 UTC, john0005 commented
Let me know if these works, some branches were made to get this working and they should have been merged in by the time you look over this.

2016-11-04 14:12 UTC, tyle8552 commented
Looking at this today

2016-11-04 18:04 UTC, tyle8552 commented
@john0005 I don't know where those files are.

2016-11-07 09:37 UTC, john0005 commented
`Contour.gpk`, found here `\\apps-data\Data\api\javase-android-shared\gpks`

Just added this one.
`RasterHillShade.tpk`, found here `\\apps-data\Data\api\javase-android-shared\raster\formats\TPK`

2016-11-07 17:25 UTC, tyle8552 commented
Cool, I'll review this today and add those to samples data. These are approved for public use, correct?

2016-11-07 17:59 UTC, eric906 commented
@john0005 @tyle8552 Do you guys know where the data originated from? If we've shipped these before, we're good.

2016-11-07 18:03 UTC, tyle8552 commented
@eric906 No clue.

2016-11-07 18:13 UTC, eric906 commented
@tyle8552 Lets not let this stop your progress. When @ldanzinger gets back, I'll verify with him. He may have provided the data, and he is really good at knowing the attribution.

2016-11-07 20:26 UTC, mbcoder commented
@eric906 @tyle8552 the contour data is from the 10.2.4 sample application so we have used this before.

2016-11-08 09:15 UTC, john0005 commented
All the data I use in these local server samples is from 10.2.4.

2016-11-08 10:05 UTC, colinanderson commented
>@eric906 @tyle8552 the contour data is from the 10.2.4 sample application so we have used this before.

The contour GPK in \\\apps-data\Data\api\javase-android-shared\gpks was put there by me with the intention of using it in a unit test since the message in a bottle one was/is failing on Ubuntu 16. Turns out the contour one fails too. I got it from @anttikajanus but have no idea about where the file really came from or if it is the same one as we have used before.

I was going to remove it when I realised it didn't work but it is mentioned in the relevant local server issue so I left it there.

2016-11-08 19:38 UTC, ghost requested changes
Looks pretty good. A few comments and changes for when I add these files to samples data.

I don't think a gif is necessary for this one. I'll add a still image. I'd like to keep the "Developer Use Only" watermark out of the thumbnails as much as possible.

2016-11-08 19:38 UTC, ghost commented on src/main/java/com/esri/samples/localserver/local_server_geoprocessing/LocalServerGeoprocessingController.java
> +            String gpServiceURL = Paths.get(getClass().getResource("/local_server/Contour.gpk").toURI()).toString();
`String gpServiceURL = new File("./samples-data/local_server/Contour.gpk").getAbsolutePath();`

2016-11-08 19:38 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_geoprocessing/LocalServerGeoprocessingController.java
> +      String rasterURL = Paths.get(getClass().getResource("/local_server/RasterHillshade.tpk").toURI()).toString();
`String rasterURL = new File("./samples-data/local_server/RasterHillshade.tpk").getAbsolutePath();`

2016-11-08 19:38 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_geoprocessing/LocalServerGeoprocessingController.java
> +   *
empty line

2016-11-08 19:38 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_geoprocessing/LocalServerGeoprocessingController.java
> +        System.out.println("Error: " + gpJob.getError().getAdditionalMessage());
This will not be visible in sample viewer. Should probably show the message in a dialog like the editing samples.

2016-11-08 19:38 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_geoprocessing/LocalServerGeoprocessingSample.java
> +    //    controller.setHostServices(getHostServices());
remove

2016-11-08 19:38 UTC, tyle8552 commented on src/main/java/com/esri/samples/localserver/local_server_geoprocessing/LocalServerGeoprocessingSample.java
> +    //    this.getHostServices();
remove

2016-11-08 19:39 UTC, tyle8552 commented
Could you use this one instead and remove the gif?

![localservergeoprocessing](https://cloud.githubusercontent.com/assets/19919893/20114094/e709e102-a5a7-11e6-86aa-eacf4e74e702.png)

2016-11-09 01:41 UTC, anttikajanus commented
The gpk that I had is the same gpk that JC was using earlier but repackaged to 10.4 by @gayl0000. It should be fine for the sample use (if it works!)

2016-11-09 16:29 UTC, tyle8552 commented
Ok, I'll update samples-data.

2016-11-09 17:30 UTC, tyle8552 commented
@john0005 I've updated samples data. Delete your current copy and refresh to download the new version.

2016-11-10 17:22 UTC, merged