Updating version numbers
Esri/arcgis-maps-sdk-java-samples pull request #828
Opened 2024-04-03 14:16 UTC by mfeigl

### Description

Updating the version numbers in preparation for the 200.4 release

Checklist:
- [x] Set target branch to main (current release) or v.next (next release)
- [x] Request a reviewer
- [x] Assign a reviewer
- [x] Tag reviewer in comment

2024-04-03 14:16 UTC, mfeigl commented
@mbcoder could you please review?

2024-04-03 16:41 UTC, mbcoder requested changes
Spotted one lib we should consider updating, but looks good other than that

2024-04-03 16:41 UTC, mbcoder commented on editing/edit-feature-attachments/build.gradle
>      implementation 'commons-io:commons-io:2.15.0'
Consider using https://mvnrepository.com/artifact/commons-io/commons-io/2.16.0

Needs testing however

2024-04-04 12:04 UTC, mfeigl commented on editing/edit-feature-attachments/build.gradle
>      implementation 'commons-io:commons-io:2.15.0'
Updated all 7 occurences and tested a couple which ran fine

2024-04-04 13:01 UTC, mbcoder approved these changes
Looks good

2024-04-11 09:57 UTC, merged