OAuth sample.
Esri/arcgis-maps-sdk-java-samples pull request #96
Opened 2016-11-17 23:01 UTC by vGandhi

https://devtopia.esri.com/runtime/common-samples/issues/192

2016-11-18 14:23 UTC, colinanderson commented on src/main/java/com/esri/samples/portal/oauth/OAuthChallengeHandler.java
> + * To change this license header, choose License Headers in Project Properties.
Header comment looks a bit suspicious.

2016-11-18 14:23 UTC, colinanderson commented on src/main/java/com/esri/samples/portal/oauth/OAuthChallengeHandler.java
> +import com.esri.arcgisruntime.security.*;
We don't use * imports in the main code base but maybe it is allowed in samples.

2016-11-18 14:23 UTC, colinanderson commented on src/main/java/com/esri/samples/portal/oauth/OAuthChallengeHandler.java
> +}
Add the missing new line

2016-11-18 14:23 UTC, colinanderson commented on src/main/java/com/esri/samples/portal/oauth/Controller.java
> +package com.esri.samples.portal.oauth;
Does this file need a header comment?

2016-11-18 14:23 UTC, colinanderson commented on src/main/java/com/esri/samples/portal/oauth/README.md
> +    create a custom handler similar to one created in this sample <code>OAuthChallengeHandler</code>.</li>
Should it be "similar to the one" rather then "similar to one"?

2016-11-18 14:27 UTC, colinanderson commented
I haven't looked at many samples so don't know the general style but I'm wondering if a few more comments in the code might be helpful e.g.
```
// display the web page
// add listener for when web page changes
// extract the code from the URL
```
etc

2016-11-28 23:57 UTC, vGandhi commented on src/main/java/com/esri/samples/portal/oauth/OAuthChallengeHandler.java
> + * To change this license header, choose License Headers in Project Properties.
Replaced with the standard license header.

2016-11-28 23:58 UTC, vGandhi commented on src/main/java/com/esri/samples/portal/oauth/OAuthChallengeHandler.java
> +import com.esri.arcgisruntime.security.*;
Replaced with individual imports

2016-11-28 23:58 UTC, vGandhi commented on src/main/java/com/esri/samples/portal/oauth/OAuthChallengeHandler.java
> +}
Added.

2016-11-28 23:58 UTC, vGandhi commented on src/main/java/com/esri/samples/portal/oauth/Controller.java
> +package com.esri.samples.portal.oauth;
Added

2016-11-28 23:58 UTC, vGandhi commented on src/main/java/com/esri/samples/portal/oauth/README.md
> +    create a custom handler similar to one created in this sample <code>OAuthChallengeHandler</code>.</li>
Changed.

2016-11-29 00:20 UTC, tyle8552 commented
Looking at this now.

2016-12-02 00:41 UTC, tyle8552 commented
@vGandhi I think this one will need some UI tweaks. None of the other samples manage multiple views, and we try to avoid extra non-arcgis-api logic. I think I would like to take a little time towards the end of this sprint or the next sprint to rework the UI. Not your fault; the common design should have considered desktop platforms. Thanks for doing the hard bits, I've never understood OAuth very well.

2016-12-06 22:30 UTC, tyle8552 commented
@vGandhi I've made some changes. Can you please review?

2016-12-07 22:52 UTC, vGandhi commented
@tyle8552 Looks good.

2016-12-08 17:19 UTC, tyle8552 commented
Holding off on merging this until I get the Authoring a Map sample done since it also uses OAuth. Might be able to find a good common pattern and UI between them.

2016-12-21 17:15 UTC, tyle8552 commented
@john0005 Could you review? I think this is ready.

2016-12-22 11:26 UTC, john0005 commented
Will need to update were we will place this sample and the Create and Save Sample. Portal sounds like a good spot since map already has a few in it.

2016-12-22 11:36 UTC, john0005 requested changes

2016-12-22 11:36 UTC, john0005 commented on src/main/java/com/esri/samples/portal/oauth/README.md
> +
One thing that I would like to add here is the `Authentication` section like Save_and_Create has, https://github.com/Esri/arcgis-runtime-samples-java/tree/tyle8552/create_and_save_map/src/main/java/com/esri/samples/map/create_and_save_map.

We could just make a wiki page that better explains how to set the backend process up and just have these two samples link to that page.

I feel like this took me awhile to figure out and I have all the information to get it working. A user who comes across this sample might just find it to confusing to get working.

2016-12-22 11:36 UTC, john0005 commented on src/main/java/com/esri/samples/portal/oauth/README.md
> +
The wiki page could address:
  - creating an account
  - going to https://developers.arcgis.com/applications/#/ to create an application and obtaining the `Client ID:`
  - what portal URL to enter, `http://www.arcgis.com/`
  - how to setup Redirect Url `urn:ietf:wg:oauth:2.0:oob`

For the redirect url, is this something that anyone can use. If I setup an account and use this Redirect Url it works for me, so we can just explain to users how to set that Redirect Url.

I can go ahead and create this wiki page if this is the route we want to go.

2016-12-22 11:36 UTC, john0005 commented on src/main/resources/fxml/oauth_controller.fxml
> +        <VBox spacing="10" maxWidth="300">
Could add some not editable text fields below each were information is going to be displayed. I believe it looks a little better.
![oauth](https://cloud.githubusercontent.com/assets/14575538/21424024/06bab9ce-c838-11e6-88d0-1fca527fea23.PNG)

2016-12-22 11:36 UTC, john0005 commented on src/main/java/com/esri/samples/portal/oauth/README.md
> +<p>Enter the details of the application registered in ArcGIS platform. Click on sign-in.
registered in ArcGIS platform and click sign-in.

2016-12-22 11:36 UTC, john0005 commented on src/main/resources/fxml/oauth_controller.fxml
> +<!--
@tyle8552 Just a remind for both of us that we should check this is in all FXML files. I know some of mine don't have it.

2016-12-22 11:36 UTC, john0005 commented on src/main/java/com/esri/samples/portal/oauth/OAuthController.java
> +  @FXML
Feel like it looks better this way, but we can decide on that.
![fxml](https://cloud.githubusercontent.com/assets/14575538/21424284/b924024a-c839-11e6-9f1a-86f8a29f8e15.PNG)

2016-12-22 11:36 UTC, john0005 commented on src/main/java/com/esri/samples/portal/oauth/OAuthChallengeHandler.java
> +/*
Might be able to store this class in its own package and reference it from there since this and `Create and Save Sample` both use it.

2016-12-22 11:36 UTC, john0005 commented on src/main/java/com/esri/samples/portal/oauth/OAuthController.java
> +        role.setText(portal.getUser().getRole().name());
Will need to check not null. I didn't set up my role on my account and when I ran the application it threw an NullException error here.

2016-12-22 17:12 UTC, tyle8552 commented on src/main/java/com/esri/samples/portal/oauth/OAuthChallengeHandler.java
> +/*
@john0005 I think we should keep duplicates. In a real application you wouldn't duplicate, but in samples I think you want to see everything you need in one folder. Also, the sample viewer only looks in the sample folder and the fxml folder for its files list. There would be no easy rule to help it find the required files.

2016-12-22 18:00 UTC, tyle8552 commented on src/main/java/com/esri/samples/portal/oauth/README.md
> +
@john0005 I've created a wiki and added a link to it in the readme.

2016-12-22 18:01 UTC, tyle8552 commented
@john0005 I think I got everything. Changed auth details to be handled via a custom dialog similar to the Create a Map sample. Can you review again?

2016-12-23 15:55 UTC, john0005 approved these changes

2016-12-23 15:55 UTC, john0005 commented
Looks good.

2017-01-03 17:33 UTC, merged